#Classics
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Tucker 1948','Description Tucker 1948','http://www.livroandroid.com.br/livro/cars/classicos/Tucker.png','http://www.livroandroid.com.br/livro/cars/classicos/tucker.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Chevrolet Corvette','Description Chevrolet Corvette','http://www.livroandroid.com.br/livro/cars/classicos/Chevrolet_Corvette.png','http://www.livroandroid.com.br/livro/cars/classicos/corvette.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Chevrolet Impala Coupe','Description Chevrolet Impala Coupe','http://www.livroandroid.com.br/livro/cars/classicos/Chevrolet_Impala_Coupe.png','http://www.livroandroid.com.br/livro/cars/classicos/chevrolet_impala.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Cadillac Deville Convertible','Description Cadillac Deville Convertible','http://www.livroandroid.com.br/livro/cars/classicos/Cadillac_Deville_Convertible.png','http://www.livroandroid.com.br/livro/cars/classicos/cadillac_deville.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Chevrolet Bel-Air','Description Chevrolet Bel-Air','http://www.livroandroid.com.br/livro/cars/classicos/Chevrolet_BelAir.png','http://www.livroandroid.com.br/livro/cars/classicos/chevrolet_bel_air.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Cadillac Eldorado','Description Cadillac Eldorado','http://www.livroandroid.com.br/livro/cars/classicos/Cadillac_Eldorado.png','http://www.livroandroid.com.br/livro/cars/classicos/cadillac_eldorado.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Ferrari 250 GTO','Description Ferrari 250 GTO','http://www.livroandroid.com.br/livro/cars/classicos/Ferrari_250_GTO.png','http://www.livroandroid.com.br/livro/cars/classicos/ferrari_gto.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Dodge Challenger','Description Dodge Challenger','http://www.livroandroid.com.br/livro/cars/classicos/Dodge_Challenger.png','http://www.livroandroid.com.br/livro/cars/classicos/dodge_challenger.mp4','','','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Camaro SS 1969','Description Camaro SS 1969','http://www.livroandroid.com.br/livro/cars/classicos/Camaro_SS.png','http://www.livroandroid.com.br/livro/cars/classicos/camaro_ss.mp4','-23.564224','-46.653156','classic');
insert into car(name, description, url_photo,url_video, latitude, longitude, category) VALUES('Ford Mustang 1976','Description Ford Mustang 1976','http://www.livroandroid.com.br/livro/cars/classicos/Ford_Mustang.png','http://www.livroandroid.com.br/livro/cars/classicos/ford_mustang.mp4','-23.564224','-46.653156','classic');

#Sports
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Ferrari FF','Description Ferrari FF','http://www.livroandroid.com.br/livro/cars/esportivos/Ferrari_FF.png','http://www.livroandroid.com.br/livro/cars/esportivos/ferrari_ff.mp4','44.532218','10.864019','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('AUDI GT Spyder','Description AUDI GT Spyder','http://www.livroandroid.com.br/livro/cars/esportivos/Audi_Spyder.png','http://www.livroandroid.com.br/livro/cars/esportivos/audi_gt.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Porsche Panamera','Description Porsche Panamera','http://www.livroandroid.com.br/livro/cars/esportivos/Porsche_Panamera.png','http://www.livroandroid.com.br/livro/cars/esportivos/porsche_panamera.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Lamborghini Aventador','Description Lamborghini Aventador','http://www.livroandroid.com.br/livro/cars/esportivos/Lamborghini_Aventador.png','http://www.livroandroid.com.br/livro/cars/esportivos/lamborghini_aventador.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Chevrolet Corvette Z06','Description Chevrolet Corvette Z06','http://www.livroandroid.com.br/livro/cars/esportivos/Chevrolet_Corvette_Z06.png','http://www.livroandroid.com.br/livro/cars/esportivos/chevrolet_corvette.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('BMW M5','Description BMW M5','http://www.livroandroid.com.br/livro/cars/esportivos/BMW.png','http://www.livroandroid.com.br/livro/cars/esportivos/bmw-m5.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Renault Megane RS Trophy','Description Renault Megane RS Trophy','http://www.livroandroid.com.br/livro/cars/esportivos/Renault_Megane_Trophy.png','http://www.livroandroid.com.br/livro/cars/esportivos/renault_megane.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Maserati Grancabrio Sport','Description Maserati Grancabrio Sport','http://www.livroandroid.com.br/livro/cars/esportivos/Maserati_Grancabrio_Sport.png','http://www.livroandroid.com.br/livro/cars/esportivos/renault_megane.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('McLAREN MP4-12C','Description McLAREN MP4-12C','http://www.livroandroid.com.br/livro/cars/esportivos/McLAREN.png','http://www.livroandroid.com.br/livro/cars/esportivos/mcLaren.mp4','-23.564224','-46.653156','sport');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('MERCEDES-BENZ C63 AMG','Description MERCEDES-BENZ C63 AMG','http://www.livroandroid.com.br/livro/cars/esportivos/MERCEDES_BENZ_AMG.png','http://www.livroandroid.com.br/livro/cars/esportivos/mercedes.mp4','-23.564224','-46.653156','sport');

#Luxury
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Bugatti Veyron','Description Bugatti Veyron','http://www.livroandroid.com.br/livro/cars/luxo/Bugatti_Veyron.png','http://www.livroandroid.com.br/livro/cars/luxo/bugatti_veyron.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Ferrari Enzo','Description Ferrari Enzo','http://www.livroandroid.com.br/livro/cars/luxo/Ferrari_Enzo.png','http://www.livroandroid.com.br/livro/cars/luxo/ferrari_enzo.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Lamborghini Reventon','Description Lamborghini Reventon','http://www.livroandroid.com.br/livro/cars/luxo/Lamborghini_Reventon.png','http://www.livroandroid.com.br/livro/cars/luxo/lamborghini _reventon.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Leblanc Mirabeau','Description Leblanc Mirabeau','http://www.livroandroid.com.br/livro/cars/luxo/Leblanc_Mirabeau.png','http://www.livroandroid.com.br/livro/cars/luxo/leblanc_mirabeau.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Shelby Supercars Ultimate','Description Shelby Supercars Ultimate','http://www.livroandroid.com.br/livro/cars/luxo/Shelby_Supercars_Ultimate.png','http://www.livroandroid.com.br/livro/cars/luxo/shelby.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Pagani Zonda','Description Pagani Zonda','http://www.livroandroid.com.br/livro/cars/luxo/Pagani_Zonda.png','http://www.livroandroid.com.br/livro/cars/luxo/pagani_zonda.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Koenigsegg CCX','Description Koenigsegg CCX','http://www.livroandroid.com.br/livro/cars/luxo/Koenigsegg_CCX.png','http://www.livroandroid.com.br/livro/cars/luxo/koenigsegg.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Mercedes SLR McLaren','Description Mercedes SLR McLaren','http://www.livroandroid.com.br/livro/cars/luxo/Mercedes_McLaren.png','http://www.livroandroid.com.br/livro/cars/luxo/mclaren_slr.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Rolls Royce Phantom','Description Rolls Royce Phantom','http://www.livroandroid.com.br/livro/cars/luxo/Rolls_Royce_Phantom.png','http://www.livroandroid.com.br/livro/cars/luxo/rolls_royce.mp4','-23.564224','-46.653156','luxury');
insert into car(name, description, url_photo, url_video, latitude, longitude, category) VALUES('Lexus LFA','Description Lexus LFA','http://www.livroandroid.com.br/livro/cars/luxo/Lexus_LFA.png','http://www.livroandroid.com.br/livro/cars/luxo/lexus.mp4','-23.564224','-46.653156','luxury');

SELECT * FROM car;

#Count
select count(*) from car;

select id,name,category from car;
